// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX_ErpwyV2xyo5jgdMQc_VGw_1TdzG_rw',
    appId: '1:832061936141:web:31456c8a4d7809fe803b44',
    messagingSenderId: '832061936141',
    projectId: 'recipath-377c4',
    authDomain: 'recipath-377c4.firebaseapp.com',
    storageBucket: 'recipath-377c4.firebasestorage.app',
    measurementId: 'G-J7HE1RR38Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUuJrzno8UVQ7tNvrYnWq7DgAmHa8lyA',
    appId: '1:832061936141:android:3317979b488c01d6803b44',
    messagingSenderId: '832061936141',
    projectId: 'recipath-377c4',
    storageBucket: 'recipath-377c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoT08nKeLi4CC2f4s6Kw4xEzRTzyrFTHM',
    appId: '1:832061936141:ios:bff0395bc3391280803b44',
    messagingSenderId: '832061936141',
    projectId: 'recipath-377c4',
    storageBucket: 'recipath-377c4.firebasestorage.app',
    iosBundleId: 'com.cunibongames.recipeList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoT08nKeLi4CC2f4s6Kw4xEzRTzyrFTHM',
    appId: '1:832061936141:ios:bff0395bc3391280803b44',
    messagingSenderId: '832061936141',
    projectId: 'recipath-377c4',
    storageBucket: 'recipath-377c4.firebasestorage.app',
    iosBundleId: 'com.cunibongames.recipeList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX_ErpwyV2xyo5jgdMQc_VGw_1TdzG_rw',
    appId: '1:832061936141:web:2d1c3003fef7d340803b44',
    messagingSenderId: '832061936141',
    projectId: 'recipath-377c4',
    authDomain: 'recipath-377c4.firebaseapp.com',
    storageBucket: 'recipath-377c4.firebasestorage.app',
    measurementId: 'G-ZZTP51GX7Z',
  );
}
